name: .NET

on:
  push:
    branches: [ master ]
    paths:
      - 'apis/poi/**'
      - '.github/workflows/dotnet.yml'
  pull_request:
    branches: [ master ]
    paths:    
      - 'apis/poi/**'
      - '.github/workflows/dotnet.yml'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore apis/poi/poi.sln
    - name: Build
      run: dotnet build --no-restore apis/poi/poi.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal apis/poi/poi.sln      
#Opens An Issue Only When CI Fails
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
          
  docker_build_and_push:
  #if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    
    #- name: Docker login
    - shell: bash
      name: Docker Login
      env:
        ACR_KEY: ${{ secrets.ACR_KEY }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker login openhackxqzxmauhbxtiiacr.azurecr.io -u "$DOCKER_USER" -p "$ACR_KEY"
    - name: Docker build
      run: docker build -t openhackwfs1ej01acr.azurecr.io/devopsoh/api-poi:${{github.run_number}} --build-arg build_version=${{github.run_number}} apis/poi/web
    - name: Docker Push
      run: docker push openhackwfs1ej01acr.azurecr.io/devopsoh/api-poi:${{github.run_number}}
