name: POI CD

env:
  poi_path: apis/poi/**
  registry: openhackxqzxmauhbxtiiacr.azurecr.io
  repository: devopsoh/api-poi
  docker_path: apis/poi/web
  staging_url: https://openhackdevopsapp-poi-0x001-staging.azurewebsites.net
  prod_url: hhttps://openhackdevopsapp-poi-0x001.azurewebsites.net
  resource_group: rgOpenHackDevOps20
  webapp_name: openhackdevopsapp-poi-0x001
  build_name: POI
  ACR_URL: 'openhackxqzxmauhbxtiiacr.azurecr.io'
  
on:
  push:
    branches: [ master ]
    paths: 
      - apis/poi/**  
      #*** Only for dev pourpourses ;) ***
      - .github/workflows/poi_blue_green.yaml
#  pull_request:
#    branches: [ master ]
#    paths: 
#      - apis/poi/**
#      - .github/workflows/poi.yml

jobs:
#Job 1/
  docker_build_and_push:
     if: github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
     #needs: build

     steps:
     - uses: actions/checkout@v2

     - shell: bash
       name: Docker Login
       env:
         ACR_KEY: ${{ secrets.ACR_KEY }}
         DOCKER_USER: ${{ secrets.DOCKER_USER }}
         ACR: ${{ env.ACR_URL}}
       run: docker login "$ACR" -u "$DOCKER_USER" -p "$ACR_KEY"

     - shell: bash
       name: Docker Build
       env:
         ACR: ${{ env.ACR_URL}}
       run: docker build -t "$ACR"/devopsoh/api-poi:${{github.run_number}} --build-arg build_version=${{github.run_number}} apis/poi/web

     - shell: bash
       name: Docker Push
       env:
         ACR: ${{ env.ACR_URL}}      
       run: docker push "$ACR"/devopsoh/api-poi:${{github.run_number}}
       
#Job 2/
  deploy_staging:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: docker_build_and_push

    steps:

    - name: Azure authentication
      uses: azure/login@v1
      with:
        #READ FIRST!
        #https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli
        #https://docs.microsoft.com/en-us/azure/app-service/deploy-container-github-action?tabs=service-principal#configure-the-github-secret-for-authentication
        #az ad sp create-for-rbac --name "sp_openhack_devops20_ghactions" --role contributor --scopes /subscriptions/<suscription id guid>/resourcegroups/<rg name> --sdk-auth
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
        
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.webapp_name }}
        slot-name: staging
        #images: openhackxqzxmauhbxtiiacr.azurecr.io/devopsoh/api-poi:7
        images: ${{ env.registry }}/${{ env.repository }}:${{github.run_number}} 

#Job 3/
#  validate_staging:
#    if: github.ref == 'refs/heads/master'
#    runs-on: ubuntu-latest
#    needs: deploy_staging
#    steps:
    
#    - name: Tag Validation Container
#      run: docker tag devopsoh/api-poi:7 openhackxqzxmauhbxtiiacr.azurecr.io/devopsoh/api-poi:staging-v7
# docker push openhackxqzxmauhbxtiiacr.azurecr.io/devopsoh/api-poi:staging-v7

    - name: Web Validate
      env:
       URL: ${{ secrets.staging_url }}
      run: curl -s -w "%{http_code}" "$URL"/api/docs/poi ; if [ $? -lt "400" ]; then echo " 0K"; else exit 1; fi

    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Staging Web Test Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Staging Web Test Failed! ",
            body: body
          });
