name: POI CD

env:
  poi_path: apis/poi/**
  registry: docker.pkg.github.com
  repository: mdcodigo/ohdevops20
  docker_path: apis/poi/web
  staging_url: https://openhackdevopsapp-poi-0x001-staging.azurewebsites.net
  prod_url: hhttps://openhackdevopsapp-poi-0x001.azurewebsites.net
  resource_group: rgOpenHackDevOps20
  webapp_name: openhackdevopsapp-poi-0x001
  build_name: POI
  ACR_URL: 'openhackxqzxmauhbxtiiacr.azurecr.io'
  
on:
  push:
    branches: [ master ]
    paths: 
      - apis/poi/**  
#      - .github/workflows/poi.yml
#  pull_request:
#    branches: [ master ]
#    paths: 
#      - apis/poi/**
#      - .github/workflows/poi.yml

jobs:
#Job 1/
  docker_build_and_push:
     if: github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
     #needs: build

     steps:
     - uses: actions/checkout@v2

     - shell: bash
       name: Docker Login
       env:
         ACR_KEY: ${{ secrets.ACR_KEY }}
         DOCKER_USER: ${{ secrets.DOCKER_USER }}
         ACR: ${{ env.ACR_URL}}
       run: docker login "$ACR" -u "$DOCKER_USER" -p "$ACR_KEY"

     - shell: bash
       name: Docker Build
       env:
         ACR: ${{ env.ACR_URL}}
       run: docker build -t "$ACR"/devopsoh/api-poi:${{github.run_number}} --build-arg build_version=${{github.run_number}} apis/poi/web

     - shell: bash
       name: Docker Push
       env:
         ACR: ${{ env.ACR_URL}}      
       run: docker push "$ACR"/devopsoh/api-poi:${{github.run_number}}
       
#Job 2/
  deploy_staging:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
    - name: Azure authentication
      uses: azure/login@v1
      with:
        #READ FIRST!
        #https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli
        #https://docs.microsoft.com/en-us/azure/app-service/deploy-container-github-action?tabs=service-principal#configure-the-github-secret-for-authentication
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
