name: POI SELENIUM TESTS

env:
  poi_path: apis/poi/**
  registry: openhackxqzxmauhbxtiiacr.azurecr.io
  repository: devopsoh/api-poi
  docker_path: apis/poi/web
  staging_url: https://openhackdevopsapp-poi-0x001-staging.azurewebsites.net
  prod_url: hhttps://openhackdevopsapp-poi-0x001.azurewebsites.net
  resource_group: rgOpenHackDevOps20
  webapp_name: openhackdevopsapp-poi-0x001
  build_name: POI
  ACR_URL: 'openhackxqzxmauhbxtiiacr.azurecr.io'
  
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'N/A'


jobs:
#Job 1/
  selenium_tests:
     name: Selenium Tests
     runs-on: ubuntu-latest
     #needs: build

     steps:
     - uses: actions/checkout@v2

#     - shell: bash
#       name: Install Chrome
#       run: |
#        chmod +x ./apis/poi/tests/UiTests/InstallChrome.sh
#        ./apis/poi/tests/UiTests/InstallChrome.sh
        
     - shell: bash
       name: Install Chromer Driver & Selenium Side Runner
       run: |
        npm install -g chromedriver
        npm install -g selenium-side-runner
       
     - shell: bash
       name: Cat openhackdevopsapp-poi.side
       run: cat apis/poi/tests/UiTests/openhackdevopsapp-poi.side
       #run: ls -R -G
      
     - shell: bash
       name: Run Selenium UI Tests
       run: selenium-side-runner -c "browserName=chrome chromeOptions.args=[headless, disable-gpu]" apis/poi/tests/UiTests/openhackdevopsapp-poi.side --debug
