name: POI SELENIUM TESTS

env:
  poi_path: apis/poi/**
  registry: openhackxqzxmauhbxtiiacr.azurecr.io
  repository: devopsoh/api-poi
  docker_path: apis/poi/web
  staging_url: https://openhackdevopsapp-poi-0x001-staging.azurewebsites.net
  prod_url: hhttps://openhackdevopsapp-poi-0x001.azurewebsites.net
  resource_group: rgOpenHackDevOps20
  webapp_name: openhackdevopsapp-poi-0x001
  build_name: POI
  ACR_URL: 'openhackxqzxmauhbxtiiacr.azurecr.io'
  
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'N/A'


jobs:
#Job 1/
  selenium_tests:
     name: Selenium Tests
     runs-on: ubuntu-latest
     #needs: build

     steps:
     - uses: actions/checkout@v2

     - name: Install Selenium & Pytest
       run: |
        sudo pip3 install selenium
        sudo pip3 install pytest
       
     - name: Run Test - Swagger Health Probe
       run: pytest apis/poi/tests/UiTests/testSwaggerHealthProbe.py
        
     - shell: bash
       name: Install Selenium Side Runner
       run:  npm install -g selenium-side-runner      
      
     - shell: bash
       name: Run Test - Selenium UI Tests
       run: selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless, disable-gpu, disable-extensions, disable-dev-shm-usage, no-sandbox]" apis/poi/tests/UiTests/openhackdevopsapp-poi.side --debug
